{{- if and (not .Values.canary.enabled) (not .Values.blueGreen.enabled) -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  {{- with .Values.deployAnnotations }}
  annotations:
    {{- toYaml . | nindent 8 }}
  {{- end }}
  name: {{ include "deploy.fullname" . }}
  labels:
    {{- include "deploy.labels" . | nindent 4 }}
    {{- toYaml .Values.deployLabels | nindent 4 }}
  namespace: {{ .Values.namespace}}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "deploy.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "deploy.selectorLabels" . | nindent 8 }}
        {{- toYaml .Values.podLabels | nindent 8 }}
    spec:
      automountServiceAccountToken: false
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "deploy.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            {{- range .Values.containerPorts }}
            - name: {{ default "http" .name }}
              containerPort: {{ default "80" .containerPort }}
              protocol: {{ default "TCP" .protocol }}
            {{- end }}
          livenessProbe:
          {{- toYaml .Values.livenessProbe | nindent 12}}
          readinessProbe:
          {{- toYaml .Values.readinessProbe | nindent 12}}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
            {{- with .Values.volumeMounts }}
          volumeMounts:
              {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- with .Values.env }}
          env:
          {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}      
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}